version: "3.8" #specifies docker compose version

services:
  si-rene-be:
    image: si-rene-be
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    ports:
      - "8000:8000"
    env_file: ../../.env
    command: npm run start
# docker tag si-rene-be:latest asia-southeast1-docker.pkg.dev/si-rene-app/si-rene-be/si-rene-be:latest
# docker push asia-southeast1-docker.pkg.dev/si-rene-app/si-rene-be/si-rene-be:latest
