version: "3.8" #specifies docker compose version

services:
  si-rene-be:
    image: si-rene-be
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    ports:
      - "8080:8000"
    env_file: ../../.env
    command: npm run start
